allKeynotes:
  - id: 0
    name: Geisa Silva
    biography_text:
      - br: >-
          Educadora popular e Mestranda em Comunicação pelo POSCOM-UFBA, integrante dos grupos de pesquisa Gig@-UFBA e Meninas Digitais-BA, carpinteira do universo no <a href="https://www.instagram.com/raulhackerclub/" target="_blank" rel="noopener noreferrer">Raul Hacker Clube</a> e desenvolvedora de projetos de infraestruturas para autonomia feminista na Coletiva Periféricas.
      - en: >-
          Popular educator and master's student in Communication at POSCOM-UFBA, member of the research groups Gig@-UFBA and Meninas Digitais-BA, universe carpenter at <a href="https://www.instagram.com/raulhackerclub/" target="_blank" rel="noopener noreferrer">Raul Hacker Clube</a>, and developer of infrastructure projects for feminist autonomy at Coletiva Periféricas.
      - es: >-
          Educadora popular y estudiante de maestría en Comunicación en POSCOM-UFBA, integrante de los grupos de investigación Gig@-UFBA y Meninas Digitais-BA, carpintera del universo en <a href="https://www.instagram.com/raulhackerclub/" target="_blank" rel="noopener noreferrer">Raul Hacker Clube</a> y desarrolladora de proyectos de infraestructuras para la autonomía feminista en Coletiva Periféricas.
    photo: "keynotesImgs/defaultImg/Geisa_Silva.jpg"
    dot_photo: "keynotesImgs/dotImg/Geisa_Silva.jpg"
    github_url: ""
    instagram_url: "https://www.instagram.com/geisasantos/"
    linkedin_url: "https://www.linkedin.com/in/geisasantos"
    site_url: ""
  - id: 1
    name: Camila maia
    biography_text:
      - br: >-
          Engenheira de software, especialista em Developer Experience e apaixonada por código aberto, Camila também é cofundadora da
          <a href="https://cumbuca.dev/" target="_blank" rel="noopener noreferrer">Cumbuca Dev</a>,
          comunidade que trabalha para tornar o open source mais acessível e inclusivo no Brasil.
      - en: >-
          Software engineer, specialist in Developer Experience, and passionate about open source, Camila is also a co-founder of
          <a href="https://cumbuca.dev/" target="_blank" rel="noopener noreferrer">Cumbuca Dev</a>,
          a community that works to make open source more accessible and inclusive in Brazil.
      - es: >-
          Ingeniera de software, especialista en Developer Experience y apasionada por el código abierto, Camila también es cofundadora de
          <a href="https://cumbuca.dev/" target="_blank" rel="noopener noreferrer">Cumbuca Dev</a>,
          una comunidad que trabaja para hacer que el open source sea más accesible e inclusivo en Brasil.
    photo: "keynotesImgs/defaultImg/Camila_Maia.jpg"
    dot_photo: "keynotesImgs/dotImg/Camila_Maia.jpg"
    github_url: "https://github.com/camilamaia"
    instagram_url: "https://www.instagram.com/cmaiacd/"
    linkedin_url: "https://www.linkedin.com/in/cmaiacd/"
    site_url: "https://cumbuca.dev/"