allKeynotes:
  - id: 0
    name: Geisa Silva
    biography_text:
      - br: >-
          Educadora popular e Mestranda em Comunicação pelo POSCOM-UFBA, integrante dos grupos de pesquisa Gig@-UFBA e Meninas Digitais-BA, carpinteira do universo no <a href="https://www.instagram.com/raulhackerclub/" target="_blank" rel="noopener noreferrer">Raul Hacker Clube</a> e desenvolvedora de projetos de infraestruturas para autonomia feminista na Coletiva Periféricas.
      - en: >-
          Popular educator and master's student in Communication at POSCOM-UFBA, member of the research groups Gig@-UFBA and Meninas Digitais-BA, universe carpenter at <a href="https://www.instagram.com/raulhackerclub/" target="_blank" rel="noopener noreferrer">Raul Hacker Clube</a>, and developer of infrastructure projects for feminist autonomy at Coletiva Periféricas.
      - es: >-
          Educadora popular y estudiante de maestría en Comunicación en POSCOM-UFBA, integrante de los grupos de investigación Gig@-UFBA y Meninas Digitais-BA, carpintera del universo en <a href="https://www.instagram.com/raulhackerclub/" target="_blank" rel="noopener noreferrer">Raul Hacker Clube</a> y desarrolladora de proyectos de infraestructuras para la autonomía feminista en Coletiva Periféricas.
    photo: "keynotesImgs/defaultImg/Geisa_Silva.jpg"
    dot_photo: "keynotesImgs/dotImg/Geisa_Silva.jpg"
    github_url: ""
    instagram_url: "https://www.instagram.com/geisasantos/"
    linkedin_url: "https://www.linkedin.com/in/geisasantos"
    site_url: ""
  - id: 1
    name: Camila maia
    biography_text:
      - br: >-
          Engenheira de software, especialista em Developer Experience e apaixonada por código aberto, Camila também é cofundadora da
          <a href="https://cumbuca.dev/" target="_blank" rel="noopener noreferrer">Cumbuca Dev</a>,
          comunidade que trabalha para tornar o open source mais acessível e inclusivo no Brasil.
      - en: >-
          Software engineer, specialist in Developer Experience, and passionate about open source, Camila is also a co-founder of
          <a href="https://cumbuca.dev/" target="_blank" rel="noopener noreferrer">Cumbuca Dev</a>,
          a community that works to make open source more accessible and inclusive in Brazil.
      - es: >-
          Ingeniera de software, especialista en Developer Experience y apasionada por el código abierto, Camila también es cofundadora de
          <a href="https://cumbuca.dev/" target="_blank" rel="noopener noreferrer">Cumbuca Dev</a>,
          una comunidad que trabaja para hacer que el open source sea más accesible e inclusivo en Brasil.
    photo: "keynotesImgs/defaultImg/Camila_Maia.jpg"
    dot_photo: "keynotesImgs/dotImg/Camila_Maia.jpg"
    github_url: "https://github.com/camilamaia"
    instagram_url: "https://www.instagram.com/cmaiacd/"
    linkedin_url: "https://www.linkedin.com/in/cmaiacd/"
    site_url: "https://cumbuca.dev/"
  - id: 2
    name: Caio Gomes
    biography_text:
      - br: >-
          Físico e especialista em Machine Learning e inteligência artificial, Caio Gomes tem uma trajetória incrível liderando times e produtos de IA em empresas como Amazon, Booking.com e Nubank. Atualmente, é Chief Data & Analytics Officer e Chief Artificial Intelligence Officer do grupo Magalu.
      - en: >-
          A physicist and Machine Learning and Artificial Intelligence specialist, Caio Gomes has an impressive track record of leading AI teams and products at companies such as Amazon, Booking.com, and Nubank. He is currently the Chief Data & Analytics Officer and Chief Artificial Intelligence Officer at Magalu Group.
      - es: >-
          Físico y especialista en Machine Learning e Inteligencia Artificial, Caio Gomes cuenta con una trayectoria destacada liderando equipos y productos de IA en empresas como Amazon, Booking.com y Nubank. Actualmente, es Chief Data & Analytics Officer y Chief Artificial Intelligence Officer del Grupo Magalu.
    photo: "keynotesImgs/defaultImg/Caio_Gomes.png"
    dot_photo: "keynotesImgs/dotImg/Caio_Gomes.png"
    github_url: ""
    instagram_url: "https://www.instagram.com/mr_caiogomes/"
    linkedin_url: "https://www.linkedin.com/in/caiokylegomes/"
    site_url: ""
  - id: 3
    name: Karo Ladino-Puerto
    biography_text:
      - br: >-
          Engenheira em Robótica, eterna estudante, líder de comunidade, PSF Fellow e cofundadora da Fundação Átoma. Karobot está à frente da PyLadies Colômbia desde 2018. Hoje faz parte do time que lidera a Python Colômbia e segue criando redes para sustentar e crescer na e com a tecnologia.
      - en: >-
          Robotics Engineer, lifelong learner, community leader, PSF Fellow, and co-founder of the Átoma Foundation. Karobot has been leading PyLadies Colombia since 2018. Today, she is part of the team leading Python Colombia and continues to build networks that support and foster growth in and through technology.
      - es: >-
          Ingeniera en Robótica, eterna estudiante, líder comunitaria, PSF Fellow y cofundadora de la Fundación Átoma. Karobot lidera PyLadies Colombia desde 2018. Actualmente, forma parte del equipo que lidera Python Colombia y continúa creando redes para apoyar y fomentar el crecimiento en y a través de la tecnología.
    photo: "keynotesImgs/defaultImg/Karo_Ladino.jpg"
    dot_photo: "keynotesImgs/dotImg/Karo_Ladino.jpg"
    github_url: ""
    instagram_url: "https://www.instagram.com/karobot.co/"
    linkedin_url: "https://www.linkedin.com/in/karobotco/"
    site_url: ""