allKeynotes:
  - id: 0
    name: Geisa Silva
    biography_text:
      - br: >-
          Educadora popular e Mestranda em Comunicação pelo POSCOM-UFBA, integrante dos grupos de pesquisa Gig@-UFBA e Meninas Digitais-BA, carpinteira do universo no Raul Hacker Clube e desenvolvedora de projetos de infraestruturas para autonomia feminista na Coletiva Periféricas.
      - en: >-
          Popular educator and master's student in Communication at POSCOM-UFBA, member of the research groups Gig@-UFBA and Meninas Digitais-BA, universe carpenter at Raul Hacker Clube, and developer of infrastructure projects for feminist autonomy at Coletiva Periféricas.
      - es: >-
          Educadora popular y estudiante de maestría en Comunicación en POSCOM-UFBA, integrante de los grupos de investigación Gig@-UFBA y Meninas Digitais-BA, carpintera del universo en Raul Hacker Clube y desarrolladora de proyectos de infraestructuras para la autonomía feminista en Coletiva Periféricas.
    photo: "keynotesImgs/defaultImg/Geisa_Silva.jpg"
    dot_photo: "keynotesImgs/dotImg/Geisa_Silva.jpg"
    github_url: ""
    instagram_url: ""
    linkedin_url: ""
    site_url: ""