AllSponsors:
  - ouro: "Patrocinadores Ouro"
    flag: '/Sponsors/bandeira_ouro.png'
    name:
      - br: "Ouro"
      - en: "Gold"
      - es: "Oro"
    imgMaxSize: '200px'
    sponsors:
      - name: "Aws"
        img: '/Sponsors/aws.png'
        link: 'https://aws.amazon.com/pt/'
  - prata: "Patrocinadores Prata"
    flag: '/Sponsors/bandeira_prata.png'
    name:
      - br: "Prata"
      - en: "Silver"
      - es: "Plata"
    imgMaxSize: '175px'
    sponsors:
      - name: "Pythonic Cafe"
        img: '/Sponsors/pythonic_cafe.png'
        link: 'https://pythonic.cafe/'
      - name: 'Nekt'
        img: '/Sponsors/nekt.png'
        link: 'https://www.nekt.com/'
  - bronze: "Patrocinadores Bronze"
    flag: '/Sponsors/bandeira_bronze.png'
    name:
      - br: "Bronze"
      - en: "Bronze"
      - es: "Bronce"
    imgMaxSize: '150px'
    sponsors:
      - name: "Quansight"
        img: '/Sponsors/quansight.png'
        link: 'https://www.quansight.com/'
      - name: 'Robbin'
        img: '/Sponsors/robbin.png'
        link: 'https://www.robbin.com.br/'
  - cobre: "Patrocinadores Cobre"
    flag: '/Sponsors/bandeira_cobre.png'
    name:
      - br: "Cobre"
      - en: "Copper"
      - es: "Cobre"
    imgMaxSize: '125px'
    sponsors:
      - name: 'Lincoln Loop'
        img: '/Sponsors/lincoln_loop.png'
        link: 'https://www.lincolnloop.com/'